name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: '21'

    - name: Set up Maven
      uses: actions/setup-java@v1
      with:
        java-package: maven
        java-version: '21'

    - name: Install dependencies
      run: mvn install

    - name: Run tests
      run: mvn test -Dtest="com.codemangesystem.*"
